// The three rules that keep src/engine/ops safe to extend in parallel:
//   (a) no `node:` imports — ops are bundled into the browser's web worker;
//   (b) nothing non-JSON inside an `ext` bag — clone.ts deep-copies it and serialize.ts round-trips it through JSON;
//   (c) the generated barrel matches what scripts/gen-registry.mjs produces (never hand-edit `_registry.ts`).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { familyFiles, OUT_FILE, render, SHARED } from '../scripts/gen-registry.mjs';

const OPS = 'src/engine/ops';
function opsFiles(): string[] { return fs.readdirSync(OPS).filter(f => f.endsWith('.ts')).map(f => path.join(OPS, f)); }

test('src/engine/ops imports nothing from node: (the web worker has no node builtins)', () => {
  const offenders: string[] = [];
  for (const f of opsFiles()) {
    const src = fs.readFileSync(f, 'utf8');
    for (const m of src.matchAll(/^(?!\s*\/\/).*\bfrom\s+'node:[a-z/]+'/gm)) offenders.push(`${f}: ${m[0].trim()}`);
    for (const m of src.matchAll(/^(?!\s*\/\/).*\brequire\(\s*'node:/gm)) offenders.push(`${f}: ${m[0].trim()}`);
  }
  assert.deepEqual(offenders, [], 'ops may only import engine/type modules; tooling code belongs in <family>.schema.ts or scripts/');
});

/** The whole expression an ext write assigns: from `start` to the `;` (or line end) at bracket depth 0. */
function writtenValue(src: string, start: number): string {
  let depth = 0;
  for (let i = start; i < src.length; i++) {
    const c = src[i];
    if (c === '(' || c === '[' || c === '{') depth++;
    else if (c === ')' || c === ']' || c === '}') { if (depth === 0) return src.slice(start, i); depth--; }
    else if (depth === 0 && (c === ';' || c === '\n')) return src.slice(start, i);
  }
  return src.slice(start);
}

test('src/engine/ops never puts a Set, a Map or any class instance into an ext bag (ext is JSON-plain)', () => {
  // Every shape of an ext write — `x.ext.k = <v>`, `x.ext = { k: <v> }`, `extSet(o, 'k', <v>)`, `extPush(o, 'k', <v>)`
  // — and the WHOLE assigned expression is scanned, so `{ k: new Set<string>() }` and `new Map()` are both caught.
  const starts = /(?:\.ext\b[^\n=]*=(?!=)|\b(?:extSet|extPush)\s*\()/g;
  const nonPlain = /\bnew\s+(?!Array\b)([A-Za-z_$][\w$]*)\s*[<(]/;
  const offenders: string[] = [];
  for (const f of opsFiles()) {
    const src = fs.readFileSync(f, 'utf8');
    for (const m of src.matchAll(starts)) {
      const bad = nonPlain.exec(writtenValue(src, m.index + m[0].length));
      if (bad) offenders.push(`${f}: new ${bad[1]} in ${m[0].trim()}...`);
    }
  }
  assert.deepEqual(offenders, [], 'ext must stay JSON-plain: use arrays and plain objects (see src/engine/ops/ext.ts)');
});

test('src/engine/ops/_registry.ts is what gen:registry produces (run `npm run gen:registry`)', () => {
  const onDisk = fs.readFileSync(OUT_FILE, 'utf8');
  assert.equal(onDisk, render(), 'generated barrel is stale — run `npm run gen:registry` and commit the result');
  assert.ok(onDisk.startsWith('// GENERATED by scripts/gen-registry.mjs — do not edit'), 'the barrel must carry the generated header');
  assert.equal(onDisk.includes('\r'), false, 'the generated barrel must be written with LF endings');
  // the family scan skips the underscore files, the shared plumbing (types.ts, ext.ts, chars.ts) and every *.schema.ts
  const skipped = fs.readdirSync(OPS).filter(f => f.endsWith('.ts') && !familyFiles().includes(f));
  for (const f of skipped) assert.ok(f.startsWith('_') || SHARED.has(f) || f.endsWith('.schema.ts'), `${f} should be a family but the generator skipped it`);
});
