// GENERATED by scripts/gen-registry.mjs — do not edit
// Run `npm run gen:registry` after adding, renaming or removing a file in src/cards/rules/.
//
// The parser rule registry: one file per mechanic family, folded into flat arrays that src/cards/parse.ts consults at
// each of its dispatch points — parseEffectSentence, the parseCard line loop, parseTrigger, parseCondition, parseStatic
// and parseCostPhrase. **Built-ins run first at every one of them**, and each of those ladders runs a complete
// built-ins-only pass before the pass that enables these rules, so a family only ever claims what every built-in stage
// declined. It does *not* follow that a parse can never move: the shape a rule then produces is the family's own, and
// a wide rule can pull a line out of the `unknown` bucket in a way you did not intend. `npm run parse:diff` is how
// you check — read every group it prints, not just the count.
//
// Module-evaluation order: parse.ts imports this barrel and this barrel imports the family files, so a family may only
// *type*-import parse.ts (for `OracleRow`). Everything a rule needs at runtime is handed to it on `LineCtx`.
import type { ConditionRule, CostRule, EffectRule, LineRule, RuleFamily, StaticRule, TriggerRule } from './types.js';


const GENERATED: RuleFamily[] = [];

// ---------------------------------------------------------------- flat arrays (mutated in place by rebuild())
export const EFFECT_RULES: EffectRule[] = [];
export const LINE_RULES: LineRule[] = [];
export const TRIGGER_RULES: TriggerRule[] = [];
export const CONDITION_RULES: ConditionRule[] = [];
export const STATIC_RULES: StaticRule[] = [];
export const COST_RULES: CostRule[] = [];
/** Every registered family: the generated ones in file-name order, then any registered at runtime. */
export const RULE_FAMILIES: RuleFamily[] = [];

const RUNTIME: RuleFamily[] = [];

function rebuild(): void {
  for (const a of [EFFECT_RULES, LINE_RULES, TRIGGER_RULES, CONDITION_RULES, STATIC_RULES, COST_RULES, RULE_FAMILIES] as unknown[][]) a.length = 0;
  const seen = new Set<string>();
  for (const fam of [...GENERATED, ...RUNTIME]) {
    if (seen.has(fam.name)) throw new Error(`gen:registry — duplicate parser rule family "${fam.name}" (family names must be unique)`);
    seen.add(fam.name);
    RULE_FAMILIES.push(fam);
    if (fam.effects) EFFECT_RULES.push(...fam.effects);
    if (fam.lines) LINE_RULES.push(...fam.lines);
    if (fam.triggers) TRIGGER_RULES.push(...fam.triggers);
    if (fam.conditions) CONDITION_RULES.push(...fam.conditions);
    if (fam.statics) STATIC_RULES.push(...fam.statics);
    if (fam.costs) COST_RULES.push(...fam.costs);
  }
}
rebuild();

/** Register a rule family at runtime (tests and probes); the flat arrays are rebuilt. */
export function registerRules(fam: RuleFamily): void {
  if (RULE_FAMILIES.some(f => f.name === fam.name)) throw new Error(`registerRules: "${fam.name}" is already registered`);
  RUNTIME.push(fam);
  rebuild();
}
/** Remove a runtime-registered family by name (no-op if it was not registered at runtime). */
export function unregisterRules(name: string): void {
  const i = RUNTIME.findIndex(f => f.name === name);
  if (i >= 0) { RUNTIME.splice(i, 1); rebuild(); }
}

/**
 * fnv-1a over a deterministic description of every registered rule — the families in order, each effect rule's regex
 * source and flags, each other rule's name (or its index within its family when it has none). It changes whenever a
 * family is added, removed, reordered or has a rule added/retuned, which is exactly when a parse snapshot may move.
 */
export function rulesHash(): string {
  const parts: string[] = [];
  for (const f of RULE_FAMILIES) {
    parts.push('f:' + f.name);
    for (const r of f.effects ?? []) parts.push('e:' + r.re.source + '/' + r.re.flags);
    for (const r of f.lines ?? []) parts.push('l:' + r.name);
    (f.triggers ?? []).forEach((r, i) => parts.push('t:' + (r.name ?? i)));
    (f.conditions ?? []).forEach((r, i) => parts.push('c:' + (r.name ?? i)));
    (f.statics ?? []).forEach((r, i) => parts.push('s:' + (r.name ?? i)));
    (f.costs ?? []).forEach((r, i) => parts.push('x:' + (r.name ?? i)));
  }
  let h = 0x811c9dc5;
  const s = parts.join('|');
  for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 0x01000193); }
  return (h >>> 0).toString(16).padStart(8, '0');
}

export type { ConditionRule, CostRule, EffectRule, LineCtx, LineRule, RuleFamily, StaticRule, TriggerRule } from './types.js';
