// Generated by scripts/build-mana-sprite.mjs from https://api.scryfall.com/symbology — do not edit.
export interface ManaSymbolInfo { id: string; english: string; colors: string[]; mv: number; hybrid: boolean; phyrexian: boolean; mana: boolean; cost: boolean }
export const SYMBOLS: Record<string, ManaSymbolInfo> = {
 "{T}": {
  "id": "ms-T",
  "english": "tap this permanent",
  "colors": [],
  "mv": 0,
  "hybrid": false,
  "phyrexian": false,
  "mana": false,
  "cost": false
 },
 "{Q}": {
  "id": "ms-Q",
  "english": "untap this permanent",
  "colors": [],
  "mv": 0,
  "hybrid": false,
  "phyrexian": false,
  "mana": false,
  "cost": false
 },
 "{E}": {
  "id": "ms-E",
  "english": "an energy counter",
  "colors": [],
  "mv": 0,
  "hybrid": false,
  "phyrexian": false,
  "mana": false,
  "cost": false
 },
 "{P}": {
  "id": "ms-P",
  "english": "modal budget pawprint",
  "colors": [],
  "mv": 0,
  "hybrid": false,
  "phyrexian": false,
  "mana": false,
  "cost": false
 },
 "{PW}": {
  "id": "ms-PW",
  "english": "planeswalker",
  "colors": [],
  "mv": 0,
  "hybrid": false,
  "phyrexian": false,
  "mana": false,
  "cost": false
 },
 "{CHAOS}": {
  "id": "ms-CHAOS",
  "english": "chaos",
  "colors": [],
  "mv": 0,
  "hybrid": false,
  "phyrexian": false,
  "mana": false,
  "cost": false
 },
 "{A}": {
  "id": "ms-A",
  "english": "an acorn counter",
  "colors": [],
  "mv": 0,
  "hybrid": false,
  "phyrexian": false,
  "mana": false,
  "cost": false
 },
 "{TK}": {
  "id": "ms-TK",
  "english": "a ticket counter",
  "colors": [],
  "mv": 0,
  "hybrid": false,
  "phyrexian": false,
  "mana": false,
  "cost": false
 },
 "{X}": {
  "id": "ms-X",
  "english": "X generic mana",
  "colors": [],
  "mv": 0,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{Y}": {
  "id": "ms-Y",
  "english": "Y generic mana",
  "colors": [],
  "mv": 0,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{Z}": {
  "id": "ms-Z",
  "english": "Z generic mana",
  "colors": [],
  "mv": 0,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{0}": {
  "id": "ms-0",
  "english": "zero mana",
  "colors": [],
  "mv": 0,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{½}": {
  "id": "ms-HALF",
  "english": "one-half generic mana",
  "colors": [],
  "mv": 0.5,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": false
 },
 "{1}": {
  "id": "ms-1",
  "english": "one generic mana",
  "colors": [],
  "mv": 1,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{2}": {
  "id": "ms-2",
  "english": "two generic mana",
  "colors": [],
  "mv": 2,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{3}": {
  "id": "ms-3",
  "english": "three generic mana",
  "colors": [],
  "mv": 3,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{4}": {
  "id": "ms-4",
  "english": "four generic mana",
  "colors": [],
  "mv": 4,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{5}": {
  "id": "ms-5",
  "english": "five generic mana",
  "colors": [],
  "mv": 5,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{6}": {
  "id": "ms-6",
  "english": "six generic mana",
  "colors": [],
  "mv": 6,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{7}": {
  "id": "ms-7",
  "english": "seven generic mana",
  "colors": [],
  "mv": 7,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{8}": {
  "id": "ms-8",
  "english": "eight generic mana",
  "colors": [],
  "mv": 8,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{9}": {
  "id": "ms-9",
  "english": "nine generic mana",
  "colors": [],
  "mv": 9,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{10}": {
  "id": "ms-10",
  "english": "ten generic mana",
  "colors": [],
  "mv": 10,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{11}": {
  "id": "ms-11",
  "english": "eleven generic mana",
  "colors": [],
  "mv": 11,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{12}": {
  "id": "ms-12",
  "english": "twelve generic mana",
  "colors": [],
  "mv": 12,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{13}": {
  "id": "ms-13",
  "english": "thirteen generic mana",
  "colors": [],
  "mv": 13,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{14}": {
  "id": "ms-14",
  "english": "fourteen generic mana",
  "colors": [],
  "mv": 14,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{15}": {
  "id": "ms-15",
  "english": "fifteen generic mana",
  "colors": [],
  "mv": 15,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{16}": {
  "id": "ms-16",
  "english": "sixteen generic mana",
  "colors": [],
  "mv": 16,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{17}": {
  "id": "ms-17",
  "english": "seventeen generic mana",
  "colors": [],
  "mv": 17,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": false
 },
 "{18}": {
  "id": "ms-18",
  "english": "eighteen generic mana",
  "colors": [],
  "mv": 18,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": false
 },
 "{19}": {
  "id": "ms-19",
  "english": "nineteen generic mana",
  "colors": [],
  "mv": 19,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": false
 },
 "{20}": {
  "id": "ms-20",
  "english": "twenty generic mana",
  "colors": [],
  "mv": 20,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": false
 },
 "{100}": {
  "id": "ms-100",
  "english": "one hundred generic mana",
  "colors": [],
  "mv": 100,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": false
 },
 "{1000000}": {
  "id": "ms-1000000",
  "english": "one million generic mana",
  "colors": [],
  "mv": 1000000,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{∞}": {
  "id": "ms-INF",
  "english": "infinite generic mana",
  "colors": [],
  "mv": 0,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": false
 },
 "{W/U}": {
  "id": "ms-WU",
  "english": "one white or blue mana",
  "colors": [
   "W",
   "U"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{W/B}": {
  "id": "ms-WB",
  "english": "one white or black mana",
  "colors": [
   "W",
   "B"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{B/R}": {
  "id": "ms-BR",
  "english": "one black or red mana",
  "colors": [
   "B",
   "R"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{B/G}": {
  "id": "ms-BG",
  "english": "one black or green mana",
  "colors": [
   "B",
   "G"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{U/B}": {
  "id": "ms-UB",
  "english": "one blue or black mana",
  "colors": [
   "U",
   "B"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{U/R}": {
  "id": "ms-UR",
  "english": "one blue or red mana",
  "colors": [
   "U",
   "R"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{R/G}": {
  "id": "ms-RG",
  "english": "one red or green mana",
  "colors": [
   "R",
   "G"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{R/W}": {
  "id": "ms-RW",
  "english": "one red or white mana",
  "colors": [
   "W",
   "R"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{G/W}": {
  "id": "ms-GW",
  "english": "one green or white mana",
  "colors": [
   "W",
   "G"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{G/U}": {
  "id": "ms-GU",
  "english": "one green or blue mana",
  "colors": [
   "U",
   "G"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{B/G/P}": {
  "id": "ms-BGP",
  "english": "one black mana, one green mana, or 2 life",
  "colors": [
   "B",
   "G"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": true,
  "mana": true,
  "cost": false
 },
 "{B/R/P}": {
  "id": "ms-BRP",
  "english": "one black mana, one red mana, or 2 life",
  "colors": [
   "B",
   "R"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": true,
  "mana": true,
  "cost": false
 },
 "{G/U/P}": {
  "id": "ms-GUP",
  "english": "one green mana, one blue mana, or 2 life",
  "colors": [
   "U",
   "G"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": true,
  "mana": true,
  "cost": true
 },
 "{G/W/P}": {
  "id": "ms-GWP",
  "english": "one green mana, one white mana, or 2 life",
  "colors": [
   "W",
   "G"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": true,
  "mana": true,
  "cost": true
 },
 "{R/G/P}": {
  "id": "ms-RGP",
  "english": "one red mana, one green mana, or 2 life",
  "colors": [
   "R",
   "G"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": true,
  "mana": true,
  "cost": false
 },
 "{R/W/P}": {
  "id": "ms-RWP",
  "english": "one red mana, one white mana, or 2 life",
  "colors": [
   "W",
   "R"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": true,
  "mana": true,
  "cost": false
 },
 "{U/B/P}": {
  "id": "ms-UBP",
  "english": "one blue mana, one black mana, or 2 life",
  "colors": [
   "U",
   "B"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": true,
  "mana": true,
  "cost": false
 },
 "{U/R/P}": {
  "id": "ms-URP",
  "english": "one blue mana, one red mana, or 2 life",
  "colors": [
   "U",
   "R"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": true,
  "mana": true,
  "cost": false
 },
 "{W/B/P}": {
  "id": "ms-WBP",
  "english": "one white mana, one black mana, or 2 life",
  "colors": [
   "W",
   "B"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": true,
  "mana": true,
  "cost": false
 },
 "{W/U/P}": {
  "id": "ms-WUP",
  "english": "one white mana, one blue mana, or 2 life",
  "colors": [
   "W",
   "U"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": true,
  "mana": true,
  "cost": false
 },
 "{C/W}": {
  "id": "ms-CW",
  "english": "one colorless mana or one white mana",
  "colors": [
   "W"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{C/U}": {
  "id": "ms-CU",
  "english": "one colorless mana or one blue mana",
  "colors": [
   "U"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{C/B}": {
  "id": "ms-CB",
  "english": "one colorless mana or one black mana",
  "colors": [
   "B"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{C/R}": {
  "id": "ms-CR",
  "english": "one colorless mana or one red mana",
  "colors": [
   "R"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{C/G}": {
  "id": "ms-CG",
  "english": "one colorless mana or one green mana",
  "colors": [
   "G"
  ],
  "mv": 1,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{2/W}": {
  "id": "ms-2W",
  "english": "two generic mana or one white mana",
  "colors": [
   "W"
  ],
  "mv": 2,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{2/U}": {
  "id": "ms-2U",
  "english": "two generic mana or one blue mana",
  "colors": [
   "U"
  ],
  "mv": 2,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{2/B}": {
  "id": "ms-2B",
  "english": "two generic mana or one black mana",
  "colors": [
   "B"
  ],
  "mv": 2,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{2/R}": {
  "id": "ms-2R",
  "english": "two generic mana or one red mana",
  "colors": [
   "R"
  ],
  "mv": 2,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{2/G}": {
  "id": "ms-2G",
  "english": "two generic mana or one green mana",
  "colors": [
   "G"
  ],
  "mv": 2,
  "hybrid": true,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{H}": {
  "id": "ms-H",
  "english": "one colored mana or two life",
  "colors": [],
  "mv": 1,
  "hybrid": false,
  "phyrexian": true,
  "mana": true,
  "cost": false
 },
 "{W/P}": {
  "id": "ms-WP",
  "english": "one white mana or two life",
  "colors": [
   "W"
  ],
  "mv": 1,
  "hybrid": false,
  "phyrexian": true,
  "mana": true,
  "cost": true
 },
 "{U/P}": {
  "id": "ms-UP",
  "english": "one blue mana or two life",
  "colors": [
   "U"
  ],
  "mv": 1,
  "hybrid": false,
  "phyrexian": true,
  "mana": true,
  "cost": true
 },
 "{B/P}": {
  "id": "ms-BP",
  "english": "one black mana or two life",
  "colors": [
   "B"
  ],
  "mv": 1,
  "hybrid": false,
  "phyrexian": true,
  "mana": true,
  "cost": true
 },
 "{R/P}": {
  "id": "ms-RP",
  "english": "one red mana or two life",
  "colors": [
   "R"
  ],
  "mv": 1,
  "hybrid": false,
  "phyrexian": true,
  "mana": true,
  "cost": true
 },
 "{G/P}": {
  "id": "ms-GP",
  "english": "one green mana or two life",
  "colors": [
   "G"
  ],
  "mv": 1,
  "hybrid": false,
  "phyrexian": true,
  "mana": true,
  "cost": true
 },
 "{C/P}": {
  "id": "ms-CP",
  "english": "one colorless mana or two life",
  "colors": [],
  "mv": 1,
  "hybrid": false,
  "phyrexian": true,
  "mana": true,
  "cost": true
 },
 "{HW}": {
  "id": "ms-HW",
  "english": "one-half white mana",
  "colors": [
   "W"
  ],
  "mv": 0.5,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{HR}": {
  "id": "ms-HR",
  "english": "one-half red mana",
  "colors": [
   "R"
  ],
  "mv": 0.5,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": false
 },
 "{W}": {
  "id": "ms-W",
  "english": "one white mana",
  "colors": [
   "W"
  ],
  "mv": 1,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{U}": {
  "id": "ms-U",
  "english": "one blue mana",
  "colors": [
   "U"
  ],
  "mv": 1,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{B}": {
  "id": "ms-B",
  "english": "one black mana",
  "colors": [
   "B"
  ],
  "mv": 1,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{R}": {
  "id": "ms-R",
  "english": "one red mana",
  "colors": [
   "R"
  ],
  "mv": 1,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{G}": {
  "id": "ms-G",
  "english": "one green mana",
  "colors": [
   "G"
  ],
  "mv": 1,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{C}": {
  "id": "ms-C",
  "english": "one colorless mana",
  "colors": [],
  "mv": 1,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{S}": {
  "id": "ms-S",
  "english": "one snow mana",
  "colors": [],
  "mv": 1,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{L}": {
  "id": "ms-L",
  "english": "one mana from a legendary source",
  "colors": [],
  "mv": 1,
  "hybrid": false,
  "phyrexian": false,
  "mana": true,
  "cost": true
 },
 "{D}": {
  "id": "ms-D",
  "english": "one potential land drop",
  "colors": [],
  "mv": 0,
  "hybrid": false,
  "phyrexian": false,
  "mana": false,
  "cost": true
 }
};
export const SYMBOL_COUNT = 84;
