// GENERATED by scripts/gen-registry.mjs — do not edit
// Run `npm run gen:registry` after adding, renaming or removing a `<family>.schema.ts` in src/engine/ops/.
//
// The zod half of every mechanic family, folded into flat lists: src/cards/schema.ts composes them with the core
// vocabulary (`EffectSchema = z.discriminatedUnion('op', [...core, ...FAMILY_EFFECT_VARIANTS])`, the `Amount.count` and
// `TargetSpec.kind` enums widened with FAMILY_AMOUNTS / FAMILY_TARGET_KINDS, the `AbilityCost` object extended with
// FAMILY_COST_PARTS), so a script that uses a family op passes `CardScriptChecked` — stage 1 of scripts:verify — and
// the lint, `vocab:doc` and data/scripts/schema.json know the family vocabulary. With no family the lists are empty
// and the composed schema is exactly the core.
//
// Every `src/engine/ops/<family>.schema.ts` (not underscore-prefixed) is listed, sorted by file name, and exports
// `schema: FamilySchema` (src/engine/ops/types.ts). `mergeFamilySchemas` checks the contract at import time: strict
// objects, string-literal discriminators, and every literal declared ONCE — a duplicate across two families, or
// against the core, is a hard error naming both files.
//
// TOOLING ONLY: nothing under src/engine imports this file (zod is a devDependency). Import order matters for the
// same reason src/cards/schema.ts explains: ./schema-core.js comes first, so a family that imports its leaf schemas
// from src/cards/schema.js at module scope always finds them initialised.
import type { FamilySchema } from '../engine/ops/types.js';
import { CORE_VOCABULARY, mergeFamilySchemas, type FamilySchemaEntry } from './schema-core.js';
import { schema as schema_control } from '../engine/ops/control.schema.js';
import { schema as schema_copy_clone } from '../engine/ops/copy-clone.schema.js';
import { schema as schema_cost_alter } from '../engine/ops/cost-alter.schema.js';
import { schema as schema_keyword_action } from '../engine/ops/keyword-action.schema.js';
import { schema as schema_piles_choices } from '../engine/ops/piles-choices.schema.js';
import { schema as schema_planeswalker } from '../engine/ops/planeswalker.schema.js';
import { schema as schema_replacement } from '../engine/ops/replacement.schema.js';
import { schema as schema_saga } from '../engine/ops/saga.schema.js';
import { schema as schema_transform } from '../engine/ops/transform.schema.js';

/** Every family schema with the file it came from, in file-name order. */
export const FAMILY_SCHEMA_ENTRIES: readonly FamilySchemaEntry[] = [
  { family: "control", file: "src/engine/ops/control.schema.ts", schema: schema_control },
  { family: "copy-clone", file: "src/engine/ops/copy-clone.schema.ts", schema: schema_copy_clone },
  { family: "cost-alter", file: "src/engine/ops/cost-alter.schema.ts", schema: schema_cost_alter },
  { family: "keyword-action", file: "src/engine/ops/keyword-action.schema.ts", schema: schema_keyword_action },
  { family: "piles-choices", file: "src/engine/ops/piles-choices.schema.ts", schema: schema_piles_choices },
  { family: "planeswalker", file: "src/engine/ops/planeswalker.schema.ts", schema: schema_planeswalker },
  { family: "replacement", file: "src/engine/ops/replacement.schema.ts", schema: schema_replacement },
  { family: "saga", file: "src/engine/ops/saga.schema.ts", schema: schema_saga },
  { family: "transform", file: "src/engine/ops/transform.schema.ts", schema: schema_transform },
];

/** The family schemas by family name (the file's basename, which is also the FamilyModule's `name` by convention). */
export const FAMILY_SCHEMAS: Readonly<Record<string, FamilySchema>> = Object.fromEntries(FAMILY_SCHEMA_ENTRIES.map(e => [e.family, e.schema]));

const MERGED = mergeFamilySchemas(FAMILY_SCHEMA_ENTRIES, CORE_VOCABULARY);
/** Family `Effect` variants (strict objects discriminated by `op`). */
export const FAMILY_EFFECT_VARIANTS = MERGED.effects;
/** Family `Condition` variants (`kind`). */
export const FAMILY_CONDITION_VARIANTS = MERGED.conditions;
/** Family `TriggerEvent` variants (`on`). */
export const FAMILY_TRIGGER_VARIANTS = MERGED.triggers;
/** Family `StaticEffect` variants (`kind`). */
export const FAMILY_STATIC_VARIANTS = MERGED.statics;
/** Family `Amount.count` literals. */
export const FAMILY_AMOUNTS = MERGED.amounts;
/** Family `AbilityCost` fields, each with the schema of its value. */
export const FAMILY_COST_PARTS = MERGED.costParts;
/** Family `AsEnters` variants (`kind`). */
export const FAMILY_AS_ENTERS = MERGED.asEnters;
/** Family `TargetSpec.kind` literals. */
export const FAMILY_TARGET_KINDS = MERGED.targetKinds;
